### ISSUE TITLE
Paths conflicting with `rollup-plugin-root-import`

### ISSUE THREAD

**Issue by arxpoetica** [kei-ito/rollup-plugin-glob-import#1]
Not sure which plugin is doing the overwriting, but it *seems* like it's this one since line 29 https://github.com/kei-ito/rollup-plugin-glob-import/blob/master/index.js#L29 sets a relative path instead of an absolute.

Easy fix to just set an absolute path?

See: https://github.com/mixmaxhq/rollup-plugin-root-import

**Comment by kei-ito** [comment]
It seems `rollup-plugin-root-import` doesn't depend on `rollup-plugin-glob-import`.
What is your problem?

**Comment by arxpoetica** [comment]
You're correct, they are independent plugins. I'm noting some cross-compatibility issues, and it **seems** like your plugin is the one to blame (ducks from shoe thrown at face 😹 ✌️).

Basically, `rollup-plugin-root-import` does just that, it creates absolute URLs based on a root directory that is specified in the settings. What I'm suggesting is that it appears you explicitly set a relative path on line #29 of the glob import: https://github.com/kei-ito/rollup-plugin-glob-import/blob/master/index.js#L29

Shouldn't it be an absolute path instead? That would cause less problems with other plugins I would think.

**Comment by kei-ito** [comment]
OK, I got it. First of all, the `rollup-plugin-glob-import` didn't work with absolute glob patterns.

I published [v0.0.5](https://github.com/kei-ito/rollup-plugin-glob-import/releases/tag/v0.0.5) which work with absolute glob patterns. Please check [the notes](https://github.com/kei-ito/rollup-plugin-glob-import/releases/tag/v0.0.5). Does it meet your requirements?

**Comment by arxpoetica** [comment]
Yes! That's fantastic, thank you so much!
