### ISSUE TITLE
dir globbing

### ISSUE THREAD

**Issue by burningTyger** [kei-ito/rollup-plugin-glob-import#14]
You should mention in the docs that dir globbing also works:

    src/foo/a.js
    src/foo/b.js
    src/bar/c.js
    src/bar/d.js

    import * as bas from './src/*/*.js'

This totally made my day. Thank you.

**Comment by kei-ito** [comment]
Thank you @burningTyger. I added [some examples](https://github.com/kei-ito/rollup-plugin-glob-import/tree/master/sample) that imports modules from some nested directories.

**Comment by burningTyger** [comment]
Yes, that's it. Great plugin.
One thing though, is it possible by any chance to somehow process the imported path names? I'm using your library to import an arbitrary bunch of svelte components which may or may not share the same assets. There is the possiblity of name collisions if I end up putting all assets in the same output directory so path names would help to fix that.

**Comment by kei-ito** [comment]
I agree with you. I published v0.2.0 that has `options.rename`. It'll works as you expect.

Here's an example project:
- [sample/004/rollup.config.js](https://github.com/kei-ito/rollup-plugin-glob-import/blob/47817bb582c2385226f3cea880a2bb15326f638d/sample/004/rollup.config.js)
- [sample/004/output.js](https://github.com/kei-ito/rollup-plugin-glob-import/blob/47817bb582c2385226f3cea880a2bb15326f638d/sample/004/output.js)

**Comment by burningTyger** [comment]
Wow, that's amazing. You're a life saver.

**Comment by kei-ito** [comment]
I'm also helped by this plugin.
Let me close this issue. If you find something else, please create another one.
Thank you.
