### ISSUE TITLE
rename function

### ISSUE THREAD

**Issue by burningTyger** [kei-ito/rollup-plugin-glob-import#21]
The rename option does a great job!
Would it be possible to also export an object with dir names as nested objects?

example:

    foo/a.js
    foo/b.js
    bar/c.js

    => {foo: {a: A, b: B}, bar: {c: C}}

**Comment by kei-ito** [comment]
My current plan is to add a process to resolve "foo.bar"-like name returned by the "rename()". But it may be a bad way for the concept of import/export because users can't import modules selectively. Please give me some time to think about this.
Anyway, your request makes sense. Thank you!

**Comment by kei-ito** [comment]
For the time being, put 'foo/index.js' and 'bar/index.js' and import them.
