### ISSUE TITLE
Ability to define custom ordering for glob results

### ISSUE THREAD

**Issue by tivac** [kei-ito/rollup-plugin-glob-import#25]
Would an option to be able to sort the resulting imports be something you'd be open to? I would like to be able to sort them to ensure that files higher up in the directory structure come before lower ones, currently the ordering seems to be "whatever glob returns".

It seems like it could be as simple as providing a comparator function that can be passed directly to `Array.prototype.sort` if it's defined. Thoughts?

**Comment by kei-ito** [comment]
The feature won't make things better. Troubles about import/export should be resolved by right declarations of dependencies. If you have a module "M1" and it should be loaded before "M2", "M1" depends on "M2". Therefore "M1" should have a line below:

```
import "M2";
```

There's a package to sort the declarations: https://atom.io/packages/atom-import-sort . Sorting doesn't change how it works. It is just how the code looks.

**Comment by tivac** [comment]
You're right that I wouldn't need to care about this if I was manually importing all of them in the right order.

The whole point of being able to use a glob in an `import` statement is that I don't want to have to manually specify all of the dependencies though. I'd like to have a directory tree of modules that I can easily load in a single line and will be run in a consistent order, hence my request for an ability to sort the glob results.

**Comment by kei-ito** [comment]
About isolating the order of sources from the glob implementation, I agree with you. But these are not sufficient reasons to add a new option just for sorting if the plugin sorts the sources.
I published v0.2.3. It has `options.intercept` to transform the list. Please take a look at the option. It'll satisfy your requirements.

**Comment by tivac** [comment]
That should work perfectly, thanks!
